# h2 database web으로 확인
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  # spring - h2 연결
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/spring-h2-db # embedded Mode : db 데이터 저장 위치 :  ~/spring-h2-db , # in memory mode -> jdbc:h2:mem:test
    username: sa
    password:

  sql:
    init:
      mode: always
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql  # resources/data.sqltsq

test: test
